version: '2'
services:
  web:
    build: ./Docker/web/
    environment:
      - TERM=xterm
    hostname: magento
    domainname: dev.big.hu
    volumes:
      - ./:/var/www/dev/magento
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:magento.dev.big.hu
    network_mode: bridge
    links:
      - session
      - db
  db:
    image: docker.big.hu/development/mariadb
    environment:
      - TERM=xterm
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=magento
    network_mode: bridge
    volumes:
      - ./Docker/db/data:/var/lib/mysql
  session:
    image: docker.big.hu/development/memcached
    network_mode: bridge
