version: '2'
services:
  web:
    build: ./.docker/web/
    environment:
      - TERM=xterm
    hostname: magento2
    domainname: dev.big.hu
    volumes:
      - ./:/var/www/dev/magento2
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:magento2.dev.big.hu
    network_mode: bridge
    links:
      - db
      - mailcatcher
      - session
  db:
    image: docker.big.hu/development/mariadb
    environment:
      - TERM=xterm
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=magento
    network_mode: bridge
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  mailcatcher:
    image: docker.big.hu/development/mailcatcher
    network_mode: bridge
    labels:
      - traefik.enable=true
      - traefik.port=1080
      - traefik.frontend.rule=Host:magento-mail.dev.big.hu
  session:
    image: docker.big.hu/development/memcached
    network_mode: bridge

volumes:
  db_data:
